/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package singleThreadedwordproject;

import java.io.File;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        timeKeeper timer = new timeKeeper();
        long lengthCounter = 0;
        int wordCounter = 0;
        String word;
        
        File wordObj = new File("D:\\Java-software\\words-medium.txt");
        try {
            Scanner reader = new Scanner(wordObj);
            timer.startTimer();
            while (reader.hasNext()) {
                word = reader.nextLine();
                wordCounter++;
                lengthCounter += word.length();
            }
            
            long elapseTime = timer.elpasedTime();
            System.out.println("Total amount of words: " + wordCounter);
            System.out.println("Average word length is: " + lengthCounter / wordCounter);
            System.out.println("Total elapsed time is: " + elapseTime);
            reader.close();
            
        } catch (Exception e) {
            System.out.println("An error occured");
        }
    }
}
